---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zzccc.
--- DateTime: 2023/9/2 17:06
---
local common = require "kong.plugins.request-transformer.migrations.common"

return {
  {
    name = "2023-09-07-120000_request-transformer-advanced-rename",
    up   = common.rt_rename,
    down = function() end,
  },
}
